# Generated by Django 5.2 on 2025-04-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobre', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='XinaModel',
        ),
    ]
