# Generated by Django 5.2 on 2025-04-25 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0004_alter_community_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='nome',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
