# Generated by Django 5.2 on 2025-04-28 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0005_alter_community_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='nome_tag',
            field=models.CharField(default='bens', max_length=104, unique=True, validators=[django.core.validators.MinLengthValidator(9)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
